Config = {}

Config.Locations = {
    ["vehiclegundealer"] = {
        label = "Car Spawn",
        coords = {x = -1522.0206, y = 99.0061, z = 56.7121},
    },
    ["gundealerweapons"] = {
        label = "Gun Dealer Armory",
        coords = {x = -1520.4961, y = 109.6679, z = 50.0273},
    },
    ["stashgundealer"] = {
        label = "Gun Dealer Stash",
        coords = {x = -1531.7507, y = 142.8325, z = 55.6681},
    },
}

Config.Vehicles = {
    ["contender"] = "contender",
    ["dubsta"] = "dubsta",

}

Config.GunDealer = {
    label = "Gun Dealer Armory",
    slots = 30,
    items = {
        [1] = {
            name = "weapon_knife",
            price = 4000,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "weapon_switchblade",
            price = 4500,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "weapon_pistol",
            price = 30000,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "weapon_pistol50",
            price = 35000,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "weapon_combatpistol",
            price = 35000,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "weapon_vintagepistol",
            price = 40000,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "weapon_navyrevolver",
            price = 60000,
            amount = 50,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "weapon_revolver",
            price = 70000,
            amount = 50,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "weapon_assaultrifle",
            price = 500000,
            amount = 50,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "weapon_advancedrifle",
            price = 1000000,
            amount = 50,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "weapon_assaultrifle_mk2",
            price = 1500000,
            amount = 50,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "weapon_heavypistol",
            price = 50000,
            amount = 50,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "weapon_smg",
            price = 300000,
            amount = 50,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "pistol_ammo",
            price = 50,
            amount = 1000,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "rifle_ammo",
            price = 50,
            amount = 2500,
            info = {},
            type = "item",
            slot = 15,
        },
        [16] = {
            name = "smg_ammo",
            price = 50,
            amount = 1750,
            info = {},
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "pistol_suppressor",
            price = 3000,
            amount = 1000,
            info = {},
            type = "item",
            slot = 17,
        },
        [18] = {
            name = "pistol_extendedclip",
            price = 3000,
            amount = 1000,
            info = {},
            type = "item",
            slot = 18,
        },
        [19] = {
            name = "smg_extendedclip",
            price = 5000,
            amount = 1000,
            info = {},
            type = "item",
            slot = 19,
        },
        [20] = {
            name = "smg_flashlight",
            price = 3000,
            amount = 1000,
            info = {},
            type = "item",
            slot = 20,
        },
        [21] = {
            name = "smg_scope",
            price = 3500,
            amount = 1000,
            info = {},
            type = "item",
            slot = 21,
        },
        [22] = {
            name = "smg_suppressor",
            price = 4500,
            amount = 1000,
            info = {},
            type = "item",
            slot = 22,
        },
        [23] = {
            name = "rifle_extendedclip",
            price = 3000,
            amount = 1000,
            info = {},
            type = "item",
            slot = 23,
        },
        [24] = {
            name = "rifle_drummag",
            price = 3000,
            amount = 1000,
            info = {},
            type = "item",
            slot = 24,
        },
        [25] = {
            name = "rifle_suppressor",
            price = 5000,
            amount = 1000,
            info = {},
            type = "item",
            slot = 25,
        },
    }
}